source .env
BUY_YEAR_RAW=$(curl -s -L $MB_DATA_API | jq -r .price)
BUY_YEAR=$( printf "%.0f" $BUY_YEAR_RAW )
DAYS_PASSED=$((10#$(date +%j)))
EXPECT_BUY=$((BUY_YEAR / YEAR_TO_DAY))
EXPECTED_BUY_TODAY_USD=$((DAYS_PASSED*EXPECT_BUY))
EXPECTED_BUY_TODAY=$(bc -l <<< "$EXPECTED_BUY_TODAY_USD / $BUY_YEAR - $ALREADY_BOUGTH - $ALREADY_BOUGTH_2")
EXPECTED_BUY_TODAY_FIXED=$(bc -l <<< "$TOTAL_AMOUNT_FORMATTED / $YEAR_TO_DAY * $DAYS_PASSED - $ALREADY_BOUGTH - $ALREADY_BOUGTH_2")
EXPECTED_BUY_TODAY_USD=$(bc -l <<< "$BUY_YEAR * $EXPECTED_BUY_TODAY")
EXPECTED_BUY_TODAY_FIXED_USD=$(bc -l <<< "$BUY_YEAR * $EXPECTED_BUY_TODAY_FIXED")
echo "DAY: $DAYS_PASSED/$YEAR_TO_DAY"
echo "USD: $EXPECTED_BUY_TODAY_USD"
echo "MIN: 0$EXPECTED_BUY_TODAY"
echo "MAX: 0$EXPECTED_BUY_TODAY_FIXED"
echo "UMN: $EXPECTED_BUY_TODAY_USD"
echo "UMX: $EXPECTED_BUY_TODAY_FIXED_USD"
